travis:
  secure:
    BINSTAR_TOKEN: jp+36fstQgMQL3mM7K72b1nX4uNH2nhcqhv1LdQD9rQ/FzrumEN16EyShbCgp5TUgeDqj+Bi2nXwsKg1wO6Tfrel+2oXxXyjO6RXo1oupQ5biaWRvRHs3n9XLin+faevuciOejvGT8byD2l49f4/8mkZ/YpZQiJF1YY3X0qPfvdvOMzbBhY+3Cf4OOiIKukGtMqzSUeMyCcUUnHAwy9GG5jJrZA3n1edQ99rdIA7DkP6f/fht2gu5wPeTq8t9ipy6gMrOd7EYIsakIHuh4JhJzxPZsfs1qlvmL9T4gcAWxHHWUA1+2Yq+MeiEhBfZXvEKwtmxPP+cdQ3pF2rVxk1Ez9CeW2LpDIYNvpWIxF3YoY/CONEkEsETjKBK2nrg2Acp4WNbnog2OC8Lay6yA8ykyZU1Rj64oU26nbAGqU0OeVngn6EI2eobFm2Vj/1lHAFnpP6O8ZcLPXUit0Zgym6FHysapVKsCfJZEA+Pp8v01m0AShYk2CCHis1KG+DKfUeoXSUKsAcEh+F6crV8TiIx9FSuqyjO6aGy8FHICTQ+G04BzcNEAUZr16Qj4jGmXkL3lI8Q2qkFt5zT5+fS2rReTw1TuuDqXEWsc/NlxZlcW/br3hV83xwXgduoRU2iT+d6BQWo2i9089C9IL9vV0yftvMrKFKRv2HAtxCq0cJTl4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
